// mobile/src/components/SessionExpirationModal.vue
<template>
  <ion-modal :is-open="isOpen" :backdrop-dismiss="false" class="session-modal">
    <ion-content class="ion-padding">
      <div class="modal-container">
        <!-- Icône -->
        <div class="modal-icon" :class="{ 'expired': isExpired }">
          <ion-icon :icon="isExpired ? alertCircleOutline : timeOutline" />
        </div>

        <!-- Titre -->
        <h2 class="modal-title">
          {{ isExpired ? 'Session expirée' : 'Session bientôt expirée' }}
        </h2>

        <!-- Message -->
        <p class="modal-message">
          <template v-if="isExpired">
            Votre session a expiré. Veuillez vous reconnecter pour continuer.
          </template>
          <template v-else>
            Votre session expire dans {{ minutesLeft }} minute{{ minutesLeft > 1 ? 's' : '' }}.
            Voulez-vous prolonger votre session ?
          </template>
        </p>

        <!-- Boutons -->
        <div class="modal-actions">
          <template v-if="isExpired">
            <ion-button expand="block" @click="$emit('reconnect')">
              Se reconnecter
            </ion-button>
          </template>
          <template v-else>
            <ion-button fill="outline" @click="$emit('logout')" :disabled="loading">
              Se déconnecter
            </ion-button>
            <ion-button expand="block" @click="$emit('extend')" :disabled="loading">
              <ion-spinner v-if="loading" name="crescent" />
              <span v-else>Prolonger la session</span>
            </ion-button>
          </template>
        </div>
      </div>
    </ion-content>
  </ion-modal>
</template>

<script setup lang="ts">
import { 
  IonModal, 
  IonContent, 
  IonButton, 
  IonIcon,
  IonSpinner 
} from '@ionic/vue';
import { alertCircleOutline, timeOutline } from 'ionicons/icons';

defineProps<{
  isOpen: boolean;
  minutesLeft: number;
  isExpired: boolean;
  loading?: boolean;
}>();

defineEmits<{
  (e: 'extend'): void;
  (e: 'logout'): void;
  (e: 'reconnect'): void;
}>();
</script>

<style scoped>
.session-modal {
  --height: auto;
  --max-height: 90%;
  --border-radius: 16px;
}

.modal-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 24px 16px;
  text-align: center;
}

.modal-icon {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  background: linear-gradient(135deg, #f59e0b 0%, #f97316 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 20px;
}

.modal-icon.expired {
  background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
}

.modal-icon ion-icon {
  font-size: 36px;
  color: white;
}

.modal-title {
  font-size: 1.5rem;
  font-weight: 600;
  color: var(--ion-text-color);
  margin: 0 0 12px;
}

.modal-message {
  font-size: 1rem;
  color: var(--ion-color-medium);
  line-height: 1.5;
  margin: 0 0 24px;
  max-width: 280px;
}

.modal-actions {
  display: flex;
  flex-direction: column;
  gap: 12px;
  width: 100%;
  max-width: 280px;
}

.modal-actions ion-button {
  --border-radius: 8px;
}
</style>

// frontend/src/components/SessionExpirationModal.jsx
import React from 'react';

/**
 * Modale affichée lorsque la session est proche de l'expiration
 * ou lorsqu'elle a expiré
 */
export default function SessionExpirationModal({ 
  isOpen, 
  minutesLeft, 
  isExpired,
  onExtend, 
  onLogout,
  loading 
}) {
  if (!isOpen) return null;

  return (
    <div className="session-modal-overlay">
      <div className="session-modal">
        <div className="session-modal-icon">
          {isExpired ? (
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="8" x2="12" y2="12" />
              <line x1="12" y1="16" x2="12.01" y2="16" />
            </svg>
          ) : (
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10" />
              <polyline points="12,6 12,12 16,14" />
            </svg>
          )}
        </div>
        
        <h2 className="session-modal-title">
          {isExpired ? 'Session expirée' : 'Session bientôt expirée'}
        </h2>
        
        <p className="session-modal-message">
          {isExpired 
            ? 'Votre session a expiré. Veuillez vous reconnecter pour continuer.'
            : `Votre session expire dans ${minutesLeft} minute${minutesLeft > 1 ? 's' : ''}. Voulez-vous prolonger votre session ?`
          }
        </p>

        <div className="session-modal-actions">
          {isExpired ? (
            <button 
              className="session-modal-btn session-modal-btn-primary"
              onClick={onLogout}
            >
              Se reconnecter
            </button>
          ) : (
            <>
              <button 
                className="session-modal-btn session-modal-btn-secondary"
                onClick={onLogout}
                disabled={loading}
              >
                Se déconnecter
              </button>
              <button 
                className="session-modal-btn session-modal-btn-primary"
                onClick={onExtend}
                disabled={loading}
              >
                {loading ? 'Prolongation...' : 'Prolonger la session'}
              </button>
            </>
          )}
        </div>
      </div>

      <style>{`
        .session-modal-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.6);
          backdrop-filter: blur(4px);
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 10000;
          animation: fadeIn 0.2s ease-out;
        }

        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }

        .session-modal {
          background: white;
          border-radius: 16px;
          padding: 32px;
          max-width: 400px;
          width: 90%;
          text-align: center;
          box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
          animation: slideUp 0.3s ease-out;
        }

        @keyframes slideUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .session-modal-icon {
          width: 64px;
          height: 64px;
          margin: 0 auto 20px;
          background: linear-gradient(135deg, #f59e0b 0%, #ef4444 100%);
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .session-modal-icon svg {
          width: 32px;
          height: 32px;
          color: white;
        }

        .session-modal-title {
          font-size: 1.5rem;
          font-weight: 600;
          color: #1f2937;
          margin: 0 0 12px;
        }

        .session-modal-message {
          color: #6b7280;
          font-size: 1rem;
          line-height: 1.5;
          margin: 0 0 24px;
        }

        .session-modal-actions {
          display: flex;
          gap: 12px;
          justify-content: center;
        }

        .session-modal-btn {
          padding: 12px 24px;
          border-radius: 8px;
          font-size: 0.95rem;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s;
          border: none;
        }

        .session-modal-btn:disabled {
          opacity: 0.6;
          cursor: not-allowed;
        }

        .session-modal-btn-primary {
          background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
          color: white;
        }

        .session-modal-btn-primary:hover:not(:disabled) {
          transform: translateY(-1px);
          box-shadow: 0 4px 12px rgba(99, 102, 241, 0.4);
        }

        .session-modal-btn-secondary {
          background: #f3f4f6;
          color: #4b5563;
        }

        .session-modal-btn-secondary:hover:not(:disabled) {
          background: #e5e7eb;
        }
      `}</style>
    </div>
  );
}
